server:
  port: 8002

spring:
  application:
    name: service-oss
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: LTAI5tKhqQEcomD9Cc4Janhi
      keysecret: tAlQ8Q438W9ZbKQIugLYgIYileEwGh
      bucketname: athuang2